<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.10240.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>

    <AssemblyName>WinPebble.PDFToImage</AssemblyName>
    <RootNamespace>WinPebble.PDFToImage</RootNamespace>
    <Product>WinPebble PDF to Image</Product>
    <Company>WinPebble</Company>
    <Authors>WinPebble</Authors>
    <AssemblyVersion>0.9.0.1</AssemblyVersion>
    <FileVersion>0.9.0.1</FileVersion>
    <Version>0.9.0-beta.1</Version>
    <InformationalVersion>0.9.0-beta.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
</Project>
